{{- if .Values.api }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.apiSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.extraAnnotations }}
  annotations:
    {{- with .Values.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  apisecret: {{ .Values.api.secret | b64enc }}
{{- end }}
