{{- if .Values.api }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.apiSecretName" . }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  apisecret: {{ .Values.api.secret | b64enc }}
{{- end }}
