{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-redis
  labels:
{{- include "atlantis.labels" . | nindent 4 }}
data:
  password: {{ .Values.redis.password | b64enc }}
{{- end }}
